apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
        - name: ecommerce-backend
          image: 961544628649.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-backend:v1
          ports:
            - containerPort: 3000
